import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/custom/NavBar";
import { AuthProvider } from "@/components/custom/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`dark ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NavBar />
          <div className="px-[60px] py-10">
            <div className="bg-card p-4 rounded-lg min-h-[450px]">
              {children}
            </div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
